export const CantonesEcuador: Array<{ id; cantones }> = [
  {
    id: 'AZ',
    cantones: [
      'CUENCA',
      'GIRÓN',
      'GUALACEO',
      'PAUTE',
      'PUCARA',
      'SAN FERNANDO',
      'SANTA ISABEL',
      'SIGSIG',
      'OÑA',
      'CHORDELEG',
      'EL PAN',
      'SEVILLA DE ORO',
      'GUACHAPALA',
      'CAMILO PONCE ENRÍQUEZ',
    ],
  },
  {
    id: 'BOL',
    cantones: [
      'GUARANDA',
      'CHILLANES',
      'CHIMBO',
      'ECHEANDÍA',
      'SAN MIGUEL',
      'CALUMA',
      'LAS NAVES',
    ],
  },
  {
    id: 'CAN',
    cantones: [
      'AZOGUES',
      'BIBLIÁN',
      'CAÑAR',
      'LA TRONCAL',
      'EL TAMBO',
      'DÉLEG',
      'SUSCAL',
    ],
  },
  {
    id: 'CAR',
    cantones: [
      'TULCÁN',
      'BOLÍVAR',
      'ESPEJO',
      'MIRA',
      'MONTÚFAR',
      'SAN PEDRO DE HUACA',
    ],
  },
  {
    id: 'COT',
    cantones: [
      'LATACUNGA',
      'LA MANÁ',
      'PANGUA',
      'PUJILI',
      'SALCEDO',
      'SAQUISILÍ',
      'SIGCHOS',
    ],
  },
  {
    id: 'CHI',
    cantones: [
      'RIOBAMBA',
      'ALAUSI',
      'COLTA',
      'CHAMBO',
      'CHUNCHI',
      'GUAMOTE',
      'GUANO',
      'PALLATANGA',
      'PENIPE',
      'CUMANDÁ',
    ],
  },
  {
    id: 'ELO',
    cantones: [
      'MACHALA',
      'ARENILLAS',
      'ATAHUALPA',
      'BALSAS',
      'CHILLA',
      'EL GUABO',
      'HUAQUILLAS',
      'MARCABELÍ',
      'PASAJE',
      'PIÑAS',
      'PORTOVELO',
      'SANTA ROSA',
      'ZARUMA',
      'LAS LAJAS',
    ],
  },
  {
    id: 'ESM',
    cantones: [
      'ESMERALDAS',
      'ELOY ALFARO',
      'MUISNE',
      'QUININDÉ',
      'SAN LORENZO',
      'ATACAMES',
      'RIOVERDE',
      'LA CONCORDIA',
    ],
  },
  {
    id: 'GUA',
    cantones: [
      'GUAYAQUIL',
      'ALFREDO BAQUERIZO MORENO (JUJÁN)',
      'BALAO',
      'BALZAR',
      'COLIMES',
      'DAULE',
      'DURÁN',
      'EL EMPALME',
      'EL TRIUNFO',
      'MILAGRO',
      'NARANJAL',
      'NARANJITO',
      'PALESTINA',
      'PEDRO CARBO',
      'SAMBORONDÓN',
      'SANTA LUCÍA',
      'SALITRE (URBINA JADO)',
      'SAN JACINTO DE YAGUACHI',
      'PLAYAS',
      'SIMÓN BOLÍVAR',
      'CORONEL MARCELINO MARIDUEÑA',
      'LOMAS DE SARGENTILLO',
      'NOBOL',
      'GENERAL ANTONIO ELIZALDE',
      'ISIDRO AYORA',
    ],
  },
  {
    id: 'IMB',
    cantones: [
      'IBARRA',
      'ANTONIO ANTE',
      'COTACACHI',
      'OTAVALO',
      'PIMAMPIRO',
      'SAN MIGUEL DE URCUQUÍ',
    ],
  },
  {
    id: 'LOJ',
    cantones: [
      'LOJA',
      'CALVAS',
      'CATAMAYO',
      'CELICA',
      'CHAGUARPAMBA',
      'ESPÍNDOLA',
      'GONZANAMÁ',
      'MACARÁ',
      'PALTAS',
      'PUYANGO',
      'SARAGURO',
      'SOZORANGA',
      'ZAPOTILLO',
      'PINDAL',
      'QUILANGA',
      'OLMEDO',
    ],
  },
  {
    id: 'LRO',
    cantones: [
      'BABAHOYO',
      'BABA',
      'MONTALVO',
      'PUEBLOVIEJO',
      'QUEVEDO',
      'URDANETA',
      'VENTANAS',
      'VÍNCES',
      'PALENQUE',
      'BUENA FÉ',
      'VALENCIA',
      'MOCACHE',
      'QUINSALOMA',
    ],
  },
  {
    id: 'MAN',
    cantones: [
      'PORTOVIEJO',
      'BOLÍVAR',
      'CHONE',
      'EL CARMEN',
      'FLAVIO ALFARO',
      'JIPIJAPA',
      'JUNÍN',
      'MANTA',
      'MONTECRISTI',
      'PAJÁN',
      'PICHINCHA',
      'ROCAFUERTE',
      'SANTA ANA',
      'SUCRE',
      'TOSAGUA',
      '24 DE MAYO',
      'PEDERNALES',
      'OLMEDO',
      'PUERTO LÓPEZ',
      'JAMA',
      'JARAMIJÓ',
      'SAN VICENTE',
    ],
  },
  {
    id: 'MSA',
    cantones: [
      'MORONA',
      'GUALAQUIZA',
      'LIMÓN INDANZA',
      'PALORA',
      'SANTIAGO',
      'SUCÚA',
      'HUAMBOYA',
      'SAN JUAN BOSCO',
      'TAISHA',
      'LOGROÑO',
      'PABLO SEXTO',
      'TIWINTZA',
    ],
  },
  {
    id: 'NAP',
    cantones: [
      'TENA',
      'ARCHIDONA',
      'EL CHACO',
      'QUIJOS',
      'CARLOS JULIO AROSEMENA TOLA',
    ],
  },
  {
    id: 'PAS',
    cantones: ['PASTAZA', 'MERA', 'SANTA CLARA', 'ARAJUNO'],
  },
  {
    id: 'PIC',
    cantones: [
      'QUITO',
      'CAYAMBE',
      'MEJIA',
      'PEDRO MONCAYO',
      'RUMIÑAHUI',
      'SAN MIGUEL DE LOS BANCOS',
      'PEDRO VICENTE MALDONADO',
      'PUERTO QUITO',
    ],
  },
  {
    id: 'TUN',
    cantones: [
      'AMBATO',
      'BAÑOS DE AGUA SANTA',
      'CEVALLOS',
      'MOCHA',
      'PATATE',
      'QUERO',
      'SAN PEDRO DE PELILEO',
      'SANTIAGO DE PÍLLARO',
      'TISALEO',
    ],
  },
  {
    id: 'ZCH',
    cantones: [
      'ZAMORA',
      'CHINCHIPE',
      'NANGARITZA',
      'YACUAMBI',
      'YANTZAZA (YANZATZA)',
      'EL PANGUI',
      'CENTINELA DEL CÓNDOR',
      'PALANDA',
      'PAQUISHA',
    ],
  },
  {
    id: 'GAL',
    cantones: ['SAN CRISTÓBAL', 'ISABELA', 'SANTA CRUZ'],
  },
  {
    id: 'SUC',
    cantones: [
      'LAGO AGRIO',
      'GONZALO PIZARRO',
      'PUTUMAYO',
      'SHUSHUFINDI',
      'SUCUMBÍOS',
      'CASCALES',
      'CUYABENO',
    ],
  },
  {
    id: 'ORE',
    cantones: ['ORELLANA', 'AGUARICO', 'LA JOYA DE LOS SACHAS', 'LORETO'],
  },
  {
    id: 'SDT',
    cantones: ['SANTO DOMINGO'],
  },
  {
    id: 'SEL',
    cantones: ['SANTA ELENA', 'LA LIBERTAD', 'SALINAS'],
  },
];

export const ProvinciasEcuador: Array<{ provincia; codigo }> = [
  {
    provincia: 'AZUAY',
    codigo: 'AZ',
  },
  {
    provincia: 'BOLIVAR',
    codigo: 'BOL',
  },
  {
    provincia: 'CAÑAR',
    codigo: 'CAN',
  },
  {
    provincia: 'CARCHI',
    codigo: 'CAR',
  },
  {
    provincia: 'COTOPAXI',
    codigo: 'COT',
  },
  {
    provincia: 'CHIMBORAZO',
    codigo: 'CHI',
  },
  {
    provincia: 'EL ORO',
    codigo: 'ELO',
  },
  {
    provincia: 'ESMERALDAS',
    codigo: 'ESM',
  },
  {
    provincia: 'GUAYAS',
    codigo: 'GUA',
  },
  {
    provincia: 'IMBABURA',
    codigo: 'IMB',
  },
  {
    provincia: 'LOJA',
    codigo: 'LOJ',
  },
  {
    provincia: 'LOS RIOS',
    codigo: 'LRO',
  },
  {
    provincia: 'MANABI',
    codigo: 'MAN',
  },
  {
    provincia: 'MORONA SANTIAGO',
    codigo: 'MSA',
  },
  {
    provincia: 'NAPO',
    codigo: 'NAP',
  },
  {
    provincia: 'PASTAZA',
    codigo: 'PAS',
  },
  {
    provincia: 'PICHINCHA',
    codigo: 'PIC',
  },
  {
    provincia: 'TUNGURAHUA',
    codigo: 'TUN',
  },
  {
    provincia: 'ZAMORA CHINCHIPE',
    codigo: 'ZCH',
  },
  {
    provincia: 'GALAPAGOS',
    codigo: 'GAL',
  },
  {
    provincia: 'SUCUMBIOS',
    codigo: 'SUC',
  },
  {
    provincia: 'ORELLANA',
    codigo: 'ORE',
  },
  {
    provincia: 'SANTO DOMINGO DE LOS TSACHILAS',
    codigo: 'SDT',
  },
  {
    provincia: 'SANTA ELENA',
    codigo: 'SEL',
  },
];
